package com.example.icompile

val RESERVED = arrayOf(
    "fun ",
    "try ",
    "return ",
    "override ",
    "String ",
    "Int ",
    "Double ",
    "Float ",
    "Char ",
    "val ",
    "var ",
    "this ",
    "object ",
    "if ",
    "else ",
    "when ",
    "is ",
    " for ",
    "while ",
    "inline ",
    "lateinit ",
    "true ",
    "false ",
    "as ",
    "in ",
    "interface ",
    "class ",
    "constructor ",
    "init ",
    "open ",
    "companion ",
    "super ",
    "throw ",
    "catch ",
    "typeof ",
    "get ",
    " by ",
    " lazy ",
    "import ",
    "property ",
    "set ",
    "receiver ",
    "where ",
    "setparam ",
    "external ",
    "data ",
    "abstract ",
    "public ",
    "private ",
    "protected ",
    "sealed ",
    "suspend ",
    "out ",
    "internal ",
    "field "
)

val SYMBOLS = arrayOf(":", "(", ")", "{", "}", ",", "\"", "\'")
val COMMENT = "//"